order = ['cv', 'wss', 'cvv', 'wral', 'wa', 'wcel', 'wf', 'wbr', 'wrex', 'cc', 'wne', 'wceq', 'co', 'cc0', 'cfv', 'c0', 'cr', 'wn',
         'csn', 'c1', 'wfn', 'cdm', 'cle', 'wex', 'cxp', 'cin', 'cmpt', 'cbs', 'caddc', 'crn', 'clt', 'wo', 'cz', 'cmul',
         'crab', 'cuni', 'cop', 'cmin', 'cn0', 'ccnv', 'cif', 'w3a', 'cres', 'cun', 'cpw', 'cn', 'cab', 'cdif', 'wal',
         'cima', 'cxr', 'wf1o', 'wfun', 'clat', 'cneg', 'c2', 'cdiv', 'ctop', 'c0g', 'ccom', 'clmod', 'crp', 'con0',
         'cuz', 'cplusg', 'cfn', 'cgrp', 'wfo', 'cen', 'word', 'cpr', 'cfz', 'wi', 'cexp', 'crg', 'wrel', 'cmap',
         'csca', 'cabs', 'cid', 'clss', 'ctopon', 'csuc', 'ciun', 'cmulr', 'cmpt2', 'cple', 'chil', 'c1st', 'c2nd',
         'com', 'wsbc', 'wf1', 'cdom', 'cpnf', 'c1o', 'copab', 'cvsca', 'wb', 'cint', 'cur', 'cxmt', 'csup', 'csb',
         'cicc', 'wreu', 'w3o', 'ctopn', 'ccnfld', 'crio', 'chash', 'c0v', 'cmnd', 'ci', 'ccn', 'cof', 'cress', 'csu',
         'cminusg', 'cdivides', 'csdm', 'c3', 'crest', 'cmnf', 'cva', 'cseq', 'cre', 'cjn', 'cgr', 'ctg', 'cnx', 'ccrd',
         'cops', 'csm', 'c4', 'cal', 'cp0', 'cioo', 'csubg', 'catm', 'col', 'cim', 'wpss', 'csubrg', 'ce', 'weu', 'csg',
         'wor', 'cghm', 'csp', 'clspn', 'cmee', 'cep', 'wmo', 'csqr', 'cablo', 'ctp', 'csh', 'cnv', 'cgi', 'cme', 'cico',
         'wtr', 'ccj', 'c6', 'crdg', 'c2o', 'ccld', 'cdr', 'wlim', 'coc', 'cort', 'cfl', 'cfil', 'cbl', 'cmgp', 'cec', 'cgsu',
         'wwe', 'cmv', 'ctb', 'cltrn', 'clog', 'c10', 'cpo', 'cds', 'c8', 'c5', 'cngp', 'cfbas', 'c0h', 'cmopn', 'clsm',
         'cq', 'cpv', 'cio', 'c9', 'cprime', 'cnt', 'clvec', 'csin', 'c7', 'cp1', 'cmpl', 'ccvr', 'wnel', 'cpm', 'cno',
         'cvol', 'ccos', 'wiso', 'coa', 'cfzo', 'crh', 'copab2', 'cdc', 'wfr', 'cmps', 'ccrg', 'ccl', 'cts', 'ctendo',
         'cprds', 'csts', 'ciin', 'cgn', 'coppr', 'cns', 'clfn', 'clc', 'covol', 'cnr', 'cnq', 'cinvr', 'ccla', 'cui',
         'cpws', 'cps1', 'cnm', 'cmo', 'cdih', 'cofr', 'cnpi', 'cixp', 'chj', 'chmeo', 'ccmn', 'ctrl', 'cplt', 'cmg',
         'cip', 'crglmod', 'clmhm', 'cii', 'ccnp', 'cqs', 'cfg', 'cxad', 'cmre', 'clsa', 'citg2', 'cdvh', 'ctps', 'cs1',
         'cphl', 'cn0v', 'cgcd', 'cfi', 'cconcat', 'ccoe', 'ccda', 'cabel', 'cnp', 'cmt', 'cmhm', 'cdgr', 'c0p', 'wpo',
         'ctx', 'comu', 'cnei', 'cmbf', 'cioc', 'cpi', 'cnmcv', 'ccod_', 'coch', 'cbtwn', 'cli', 'cedring', 'csubmnd',
         'cr1', 'cpt', 'clln', 'cfa', 'cco1', 'ccncf', 'cxme', 'cstv', 'cnlm', 'wfal', 'cpp', 'cpc', 'cer', 'cclm',
         'crngo', 'cmi', 'club', 'clsh', 'clcd', 'cha', 'cglb', 'cdom_', 'cdg1', 'ctmd', 'cply', 'cocv', 'cid_', 'cba',
         'cxne', 'cvc', 'coi', 'clo', 'ch0o', 'wtru', 'crecs', 'cpmap', 'cph', 'cotp', 'co_', 'clk', 'cdia', 'cded',
         'cch', 'c0r', 'cword', 'cqtop', 'cps', 'coml', 'cdib', 'ccgr', 'cascl', 'calg', 'wse', 'char', 'ccmp', 'wer',
         'cmq', 'cld', 'cflim', 'cbc', 'crnk', 'cordt', 'cnzr', 'cms', 'cmagm', 'cltq', 'citg', 'ccf', 'c1q', 'cnghm',
         'claut', 'cerq', 'cdomn', 'csubstr', 'cs2', 'crmx', 'cpl1', 'chdma', 'w-bnj17', 'cplr', 'cphtpy', 'cnsb', 'clm',
         'clidl', 'citg1', 'ccolin', 'crsp', 'cpjh', 'cpco', 'cnop', 'cmzp', 'cmvr', 'cmr', 'cmpd', 'clti', 'cfm', 'cflf',
         'ceq', 'cdsr', 'cdic', 'cxmu', 'cv1', 'cund', 'cumg', 'ctxp', 'csr', 'csquarenn', 'cseqom', 'cqg', 'cpolN', 'cphtpc',
         'cltrr', 'chos', 'cexid', 'c1r', 'c1p', 'czrh', 'cwdom', 'ctsr', 'ctrg', 'crmy', 'cpred', 'cplq', 'cpli', 'cmrc', 'cm1r',
         'cltp', 'cims', 'cho', 'cfrlm', 'cee', 'cdv', 'ccxp', 'cacs', 'wsmo', 'ctgp', 'crpss', 'cpsubsp', 'cplusf', 'coe', 'cod',
         'cnmo', 'clpl', 'cidl', 'chod', 'chli', 'cgim', 'ccgr3', 'casa', 'c-bnj14', 'cstf', 'cspw', 'cs3', 'crlreg', 'cplpq', 'cmp',
         'cmmul', 'cltr', 'chot', 'cgz', 'ccv', 'ccm2', 'catan', 'wac', 'cspn', 'cs6', 'cs5', 'cpresetrel', 'cnrg', 'cmpq', 'cmndo',
         'clno', 'clf', 'chvm', 'cdjh', 'ccphlo', 'ccmrcase', 'ccbn', 'ccat', 'cca', 'casin', 'cabv', 'cxrs', 'cvdwa', 'ctskm',
         'cshi', 'cs4', 'crq', 'cpgp', 'cpell1qr', 'cpell14qr', 'cpcon', 'cofs', 'cmzpcl', 'cmn1', 'clmim', 'cldil', 'clcv', 'chg',
         'cgs', 'cfield', 'ccnfn', 'ccfil', 'cbday', 'c0cv', 'cwina', 'ctsk', 'ct1', 'csplice', 'csingle', 'cscaf', 'cq1p', 'cpj1',
         'cphi', 'comi', 'cnvc', 'cnumer', 'cmd', 'clindf', 'cipo', 'cinf', 'cina', 'cimage', 'cidom', 'chmph', 'chdma1', 'cfin4',
         'cfcls', 'cdvr', 'cdvn', 'cdsmm', 'cdrng', 'cdenom', 'ccph', 'ccms', 'wcirc', 'cufil', 'cuc1p', 'ctpos', 'ctan', 'cs7',
         'crelexp', 'cqus', 'cpadd', 'cnmoo', 'cltpq', 'clpidl', 'clly', 'cline2', 'clfig', 'cifs', 'cidp', 'cibl', 'chio', 'cfrmd',
         'cevl', 'ccon', 'cbo', 'cPc', 'w-bnj19', 'w-bnj13', 'cxko', 'csymdif', 'csubgo', 'csingles', 'csem', 'cpreset', 'cpell1234qr',
         'cors', 'codu', 'cnsg', 'cnrm', 'cnotc', 'clvol', 'clincl', 'ckln', 'cimpc', 'cimas', 'cga', 'cfals', 'cdmd', 'ccss', 'ccring',
         'cconc', 'cco', 'ccau', 'cbn', 'cbic', 'cat', 'cands', 'candc', 'c3o', 'wnan', 'wbox', 'czn', 'ctlm', 'ctdrg', 'csur', 'css',
         'cscon', 'crnghom', 'crli', 'creverse', 'cpscN', 'cprrng', 'cpridl', 'cpj', 'cpellfund', 'coppg', 'cltb', 'clsp', 'clnm',
         'cgraphcase', 'cghom', 'ceu', 'ces', 'cdveca', 'cdrs', 'cdomcase', 'cdgraa', 'ccodcase', 'ccntz', 'ccnf', 'ccm', 'caltop',
         'c0o', 'cvdg', 'cuvc', 'cufl', 'cub', 'ctc', 'ct0', 'cst', 'csra', 'csmcv', 'crtrcl', 'cr1p', 'cquot', 'cpro', 'cpprod',
         'cpmtr', 'cplpr', 'cplines', 'cplcv', 'coutsideof', 'cocaN', 'cnots', 'cnmf', 'cmpr', 'clors', 'clines', 'clinds', 'clgs',
         'clbs', 'ckq', 'cipf', 'cimps', 'cigen', 'cidcase', 'chtpy', 'cgic', 'cfunpart', 'cfne', 'cfix', 'cfin3', 'cfin2', 'cefg',
         'ce1', 'cdp2', 'ccht', 'ccart', 'cbnd', 'cbis', 'cbigcup', 'cass', 'casp', 'cado', 'caa', 'c-bnj18', 'wxo', 'wunt', 'wdia',
         'wacn', 'cxps', 'cvrmd', 'cvdwp', 'cvdwm', 'cuo', 'ctrpred', 'ctotbnd', 'ctopx', 'ctmt', 'ctgrp', 'ctch', 'cstr', 'crrn',
         'crocase', 'crngiso', 'creg', 'crange', 'cram', 'cppi', 'codz', 'co1', 'cnlly', 'cnl', 'cnacs', 'cmpaa', 'cmdg', 'cmcv',
         'clpir', 'clmic', 'cline', 'cldgis', 'cismty', 'cimg', 'cig1p', 'cig', 'chsup', 'chst', 'chom', 'chlo', 'chft', 'cge',
         'cfs', 'cdir', 'cdip', 'ccup', 'ccmtN', 'ccap', 'cbr', 'cale', 'c2ndc', 'c2idl', 'c1stc', 'c-bnj16']
